const actionTypes = {
  GET_FROM_MAIN: "GET_FROM_MAIN",
  GET_FROM_WORKER: "GET_FROM_WORKER",
  SEND_FROM_MAIN_DONE: "SEND_FROM_MAIN_DONE",
  SEND_RESULTS_TO_MANAGER: "SEND_RESULTS_TO_MANAGER",
  GET_RESULTS: "GET_RESULTS",
  INCREASE_COUNTER: "INCREASE_COUNTER",
};

module.exports = actionTypes;
