export const LOAD_FACTORIES_SUCCESS = "LOAD_FACTORIES_SUCCESS";
export const LOAD_ONE_FACTORY_SUCCESS = "LOAD_ONE_FACTORY_SUCCESS";
export const UPDATE_FACTORY_SUCCESS = "UPDATE_FACTORY_SUCCESS";
export const ADD_FACTORY_SUCCESS = "ADD_FACTORY_SUCCESS";
export const DELETE_FACTORY_SUCCESS = "DELETE_FACTORY_SUCCESS";

export const LOAD_SHOES_SUCCESS = "LOAD_SHOES_SUCCESS";
export const LOAD_ONE_SHOE_SUCCESS = "LOAD_ONE_SHOE_SUCCESS";
export const UPDATE_SHOE_SUCCESS = "UPDATE_SHOE_SUCCESS";
export const ADD_SHOE_SUCCESS = "ADD_SHOE_SUCCESS";
export const DELETE_SHOE_SUCCESS = "DELETE_SHOE_SUCCESS";

export const LOAD_LACES_SUCCESS = "LOAD_LACES_SUCCESS";
export const LOAD_ONE_LACE_SUCCESS = "LOAD_ONE_LACE_SUCCESS";
export const UPDATE_LACE_SUCCESS = "UPDATE_LACE_SUCCESS";
export const ADD_LACE_SUCCESS = "ADD_LACE_SUCCESS";
export const DELETE_LACE_SUCCESS = "DELETE_LACE_SUCCESS";

export const LOAD_PROCESSES_SUCCESS = "LOAD_PROCESSES_SUCCESS";
export const LOAD_ONE_PROCESS_SUCCESS = "LOAD_ONE_PROCESS_SUCCESS";
export const UPDATE_PROCESS_SUCCESS = "UPDATE_PROCESS_SUCCESS";
export const ADD_PROCESS_SUCCESS = "ADD_PROCESS_SUCCESS";
export const DELETE_PROCESS_SUCCESS = "DELETE_PROCESS_SUCCESS";

export const LOAD_WORKERS_SUCCESS = "LOAD_WORKERS_SUCCESS";
export const UPDATE_WORKER_SUCCESS = "UPDATE_WORKER_SUCCESS";
export const ADD_WORKER_SUCCESS = "ADD_WORKER_SUCCESS";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER_SUCCESS";
